include(
	"karibu-dsl",
	"karibu-dsl-v23",
	"example",
	"karibu-dsl:karibu-dsl-testsuite",
	"karibu-dsl:karibu-dsl-testrun-vaadin14",
	"karibu-dsl-v23:tests",
	"karibu-dsl-v23:karibu-dsl-testrun-vaadin",
	"karibu-dsl-v23:karibu-dsl-testrun-vaadin-next"
)
